name: lucky_star_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  flutter_phoenix: ^1.1.1
  http: ^1.5.0
  dio: ^5.9.0
  intl: ^0.20.2
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

# ---------- APP ICON ----------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F3441"      # adminGreenLite
  adaptive_icon_foreground: "assets/splash_icon.png"

# ---------- SPLASH SCREEN ----------
flutter_native_splash:
  color: "#0F3441"                         # background color
  image: assets/splash_icon.png            # same image as icon
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit

flutter:
  uses-material-design: true

  assets:
    - assets/splash_icon.png
    - assets/fonts/
    - assets/splash/

  fonts:
    - family: Boldonse
      fonts:
        - asset: assets/fonts/Boldonse-Regular.ttf
